package stars.main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.LayoutManager;
import java.awt.RenderingHints;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JProgressBar;
import raven.drawer.Drawer;
import raven.popup.GlassPanePopup;
import stars.avatar.ImageAvatar;
import stars.drawer.MyDrawerBuilder;

public class ProjectForm extends javax.swing.JFrame implements DateFormattable, isLoadable{
    
    public void loadProjects() {
        JPanel[] projectPanels = {panelpj1, panelpj2, panelpj3, panelpj4, panelpj5};
        JLabel[] projectTexts = {project_1_text, project_2_text, project_3_text, project_4_text, project_5_text};
        JLabel[] leaderContainers = {leader_1_container, leader_2_container, leader_3_container, leader_4_container, leader_5_container};
        ImageAvatar[] imageAvatars = {imageAvatar1, imageAvatar2, imageAvatar3, imageAvatar4, imageAvatar5};
        JLabel[] deadlineTexts = {deadline_1_text, deadline_2_text, deadline_3_text, deadline_4_text, deadline_5_text};
        JLabel[] progressTexts = {progress_1_text, progress_2_text, progress_3_text, progress_4_text, progress_5_text};
        JProgressBar[] progressBars = {progress_1_bar, progress_2_bar, progress_3_bar, progress_4_bar, progress_5_bar};

        ProjectLoader projectLoader = new ProjectLoader(projectPanels, projectTexts, leaderContainers, imageAvatars, deadlineTexts, progressTexts, progressBars);
        projectLoader.loadProjects();
    }
     
    public String formatDate(String dateStr) {
        try {
            SimpleDateFormat inputFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = inputFormat.parse(dateStr);
            SimpleDateFormat outputFormat = new SimpleDateFormat("dd MMMM yyyy");
            return outputFormat.format(date);
        } catch (Exception e) {
            e.printStackTrace();
            return "Invalid Date";
        }
    }
  
    public ProjectForm() {
        GlassPanePopup.install(this);
        MyDrawerBuilder myDrawerBuilder = new MyDrawerBuilder(this, 1);
        Drawer.getInstance().setDrawerBuilder(myDrawerBuilder);
        initComponents();
        loadProjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        menuButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel7 = new javax.swing.JPanel();
        panelpj1 = new RoundedPanel(50, new Color(40, 40, 40));
        project_1_text = new javax.swing.JLabel();
        deadline_1_text = new javax.swing.JLabel();
        progress_1_bar = new javax.swing.JProgressBar();
        progress_1_text = new javax.swing.JLabel();
        leader_1_container = new javax.swing.JLabel();
        imageAvatar1 = new stars.avatar.ImageAvatar();
        panelpj2 = new RoundedPanel(50, new Color(40, 40, 40));
        project_2_text = new javax.swing.JLabel();
        deadline_2_text = new javax.swing.JLabel();
        leader_2_container = new javax.swing.JLabel();
        progress_2_text = new javax.swing.JLabel();
        progress_2_bar = new javax.swing.JProgressBar();
        imageAvatar2 = new stars.avatar.ImageAvatar();
        panelpj4 = new RoundedPanel(50, new Color(40, 40, 40));
        project_4_text = new javax.swing.JLabel();
        deadline_4_text = new javax.swing.JLabel();
        leader_4_container = new javax.swing.JLabel();
        progress_4_text = new javax.swing.JLabel();
        progress_4_bar = new javax.swing.JProgressBar();
        imageAvatar4 = new stars.avatar.ImageAvatar();
        panelpj5 = new RoundedPanel(50, new Color(40, 40, 40));
        project_5_text = new javax.swing.JLabel();
        deadline_5_text = new javax.swing.JLabel();
        progress_5_bar = new javax.swing.JProgressBar();
        progress_5_text = new javax.swing.JLabel();
        leader_5_container = new javax.swing.JLabel();
        imageAvatar5 = new stars.avatar.ImageAvatar();
        panelpj3 = new RoundedPanel(50, new Color(40, 40, 40));
        project_3_text = new javax.swing.JLabel();
        deadline_3_text = new javax.swing.JLabel();
        leader_3_container = new javax.swing.JLabel();
        progress_3_text = new javax.swing.JLabel();
        progress_3_bar = new javax.swing.JProgressBar();
        imageAvatar3 = new stars.avatar.ImageAvatar();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Restricted = new javax.swing.JPanel();

        jPanel5.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        header.setPreferredSize(new java.awt.Dimension(1024, 80));

        menuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars/drawer/icon/bars-light.png"))); // NOI18N
        menuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setText("Projects Overview");

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(menuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
            .addGroup(headerLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Content.setPreferredSize(new java.awt.Dimension(100, 653));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel7.setBackground(new java.awt.Color(40, 40, 40));
        jPanel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelpj1.setBackground(new java.awt.Color(40, 40, 40));
        panelpj1.setPreferredSize(new java.awt.Dimension(300, 284));

        project_1_text.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        project_1_text.setText("project_1_text");

        deadline_1_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deadline_1_text.setText("Deadline: deadline_container");

        progress_1_bar.setValue(67);
        progress_1_bar.setPreferredSize(new java.awt.Dimension(157, 6));

        progress_1_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progress_1_text.setText("Progress: progress_container");

        leader_1_container.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        leader_1_container.setText("Leader: leader_container");

        imageAvatar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars/image/profilepicture.jpg"))); // NOI18N

        javax.swing.GroupLayout panelpj1Layout = new javax.swing.GroupLayout(panelpj1);
        panelpj1.setLayout(panelpj1Layout);
        panelpj1Layout.setHorizontalGroup(
            panelpj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelpj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(project_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leader_1_container, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_1_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelpj1Layout.setVerticalGroup(
            panelpj1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(project_1_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leader_1_container)
                .addGap(18, 18, 18)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deadline_1_text)
                .addGap(18, 18, 18)
                .addComponent(progress_1_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_1_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelpj2.setBackground(new java.awt.Color(40, 40, 40));
        panelpj2.setPreferredSize(new java.awt.Dimension(300, 272));

        project_2_text.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        project_2_text.setText("project_2_text");

        deadline_2_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deadline_2_text.setText("Deadline: deadline_container");

        leader_2_container.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        leader_2_container.setText("Leader: leader_container");

        progress_2_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progress_2_text.setText("Progress: progress_container");

        progress_2_bar.setValue(67);
        progress_2_bar.setPreferredSize(new java.awt.Dimension(157, 6));

        imageAvatar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars/image/profilepicture.jpg"))); // NOI18N

        javax.swing.GroupLayout panelpj2Layout = new javax.swing.GroupLayout(panelpj2);
        panelpj2.setLayout(panelpj2Layout);
        panelpj2Layout.setHorizontalGroup(
            panelpj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelpj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_2_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leader_2_container, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(project_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelpj2Layout.setVerticalGroup(
            panelpj2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(project_2_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leader_2_container)
                .addGap(18, 18, 18)
                .addComponent(imageAvatar2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deadline_2_text)
                .addGap(12, 12, 12)
                .addComponent(progress_2_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_2_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelpj4.setBackground(new java.awt.Color(40, 40, 40));
        panelpj4.setPreferredSize(new java.awt.Dimension(300, 272));

        project_4_text.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        project_4_text.setText("project_4_text");

        deadline_4_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deadline_4_text.setText("Deadline: deadline_container");

        leader_4_container.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        leader_4_container.setText("Leader: leader_container");

        progress_4_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progress_4_text.setText("Progress: progress_container");

        progress_4_bar.setValue(67);
        progress_4_bar.setPreferredSize(new java.awt.Dimension(157, 6));

        imageAvatar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars/image/profilepicture.jpg"))); // NOI18N

        javax.swing.GroupLayout panelpj4Layout = new javax.swing.GroupLayout(panelpj4);
        panelpj4.setLayout(panelpj4Layout);
        panelpj4Layout.setHorizontalGroup(
            panelpj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelpj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_4_text, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_4_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline_4_text, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leader_4_container, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(project_4_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelpj4Layout.setVerticalGroup(
            panelpj4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(project_4_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leader_4_container)
                .addGap(18, 18, 18)
                .addComponent(imageAvatar4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deadline_4_text)
                .addGap(12, 12, 12)
                .addComponent(progress_4_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_4_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        panelpj5.setBackground(new java.awt.Color(40, 40, 40));
        panelpj5.setPreferredSize(new java.awt.Dimension(300, 284));

        project_5_text.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        project_5_text.setText("project_5_text");

        deadline_5_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deadline_5_text.setText("Deadline: deadline_container");

        progress_5_bar.setValue(67);
        progress_5_bar.setPreferredSize(new java.awt.Dimension(157, 6));

        progress_5_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progress_5_text.setText("Progress: progress_container");

        leader_5_container.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        leader_5_container.setText("Leader: leader_container");

        imageAvatar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars/image/profilepicture.jpg"))); // NOI18N

        javax.swing.GroupLayout panelpj5Layout = new javax.swing.GroupLayout(panelpj5);
        panelpj5.setLayout(panelpj5Layout);
        panelpj5Layout.setHorizontalGroup(
            panelpj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelpj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(project_5_text, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_5_text, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline_5_text, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leader_5_container, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imageAvatar5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_5_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelpj5Layout.setVerticalGroup(
            panelpj5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(project_5_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leader_5_container)
                .addGap(18, 18, 18)
                .addComponent(imageAvatar5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deadline_5_text)
                .addGap(18, 18, 18)
                .addComponent(progress_5_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_5_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelpj3.setBackground(new java.awt.Color(40, 40, 40));
        panelpj3.setPreferredSize(new java.awt.Dimension(300, 272));

        project_3_text.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        project_3_text.setText("project_3_text");

        deadline_3_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        deadline_3_text.setText("Deadline: deadline_container");

        leader_3_container.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        leader_3_container.setText("Leader: leader_container");

        progress_3_text.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        progress_3_text.setText("Progress: progress_container");

        progress_3_bar.setValue(67);
        progress_3_bar.setPreferredSize(new java.awt.Dimension(157, 6));

        imageAvatar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stars/image/profilepicture.jpg"))); // NOI18N

        javax.swing.GroupLayout panelpj3Layout = new javax.swing.GroupLayout(panelpj3);
        panelpj3.setLayout(panelpj3Layout);
        panelpj3Layout.setHorizontalGroup(
            panelpj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelpj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progress_3_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deadline_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leader_3_container, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(project_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );
        panelpj3Layout.setVerticalGroup(
            panelpj3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelpj3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(project_3_text, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(leader_3_container)
                .addGap(18, 18, 18)
                .addComponent(imageAvatar3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deadline_3_text)
                .addGap(12, 12, 12)
                .addComponent(progress_3_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progress_3_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelpj5, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(panelpj3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelpj4, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(panelpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(panelpj2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelpj2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelpj1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelpj4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelpj3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelpj5, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel7);

        jButton1.setText("Edit Project");
        jButton1.setMaximumSize(new java.awt.Dimension(225, 75));
        jButton1.setMinimumSize(new java.awt.Dimension(225, 75));
        jButton1.setPreferredSize(new java.awt.Dimension(225, 75));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setText("All Projects");

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ContentLayout.createSequentialGroup()
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ContentLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ContentLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 586, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Restricted.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout RestrictedLayout = new javax.swing.GroupLayout(Restricted);
        Restricted.setLayout(RestrictedLayout);
        RestrictedLayout.setHorizontalGroup(
            RestrictedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
        );
        RestrictedLayout.setVerticalGroup(
            RestrictedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Restricted, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(header, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE)
                .addComponent(Content, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 997, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Content, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(Restricted, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuButtonActionPerformed
        // TODO add your handling code here:
        Drawer.getInstance().showDrawer();
    }//GEN-LAST:event_menuButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        new AddProjectForm().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjectForm().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JPanel Restricted;
    private javax.swing.JLabel deadline_1_text;
    private javax.swing.JLabel deadline_2_text;
    private javax.swing.JLabel deadline_3_text;
    private javax.swing.JLabel deadline_4_text;
    private javax.swing.JLabel deadline_5_text;
    private javax.swing.JPanel header;
    private stars.avatar.ImageAvatar imageAvatar1;
    private stars.avatar.ImageAvatar imageAvatar2;
    private stars.avatar.ImageAvatar imageAvatar3;
    private stars.avatar.ImageAvatar imageAvatar4;
    private stars.avatar.ImageAvatar imageAvatar5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel leader_1_container;
    private javax.swing.JLabel leader_2_container;
    private javax.swing.JLabel leader_3_container;
    private javax.swing.JLabel leader_4_container;
    private javax.swing.JLabel leader_5_container;
    private javax.swing.JButton menuButton;
    private javax.swing.JPanel panelpj1;
    private javax.swing.JPanel panelpj2;
    private javax.swing.JPanel panelpj3;
    private javax.swing.JPanel panelpj4;
    private javax.swing.JPanel panelpj5;
    private javax.swing.JProgressBar progress_1_bar;
    private javax.swing.JLabel progress_1_text;
    private javax.swing.JProgressBar progress_2_bar;
    private javax.swing.JLabel progress_2_text;
    private javax.swing.JProgressBar progress_3_bar;
    private javax.swing.JLabel progress_3_text;
    private javax.swing.JProgressBar progress_4_bar;
    private javax.swing.JLabel progress_4_text;
    private javax.swing.JProgressBar progress_5_bar;
    private javax.swing.JLabel progress_5_text;
    private javax.swing.JLabel project_1_text;
    private javax.swing.JLabel project_2_text;
    private javax.swing.JLabel project_3_text;
    private javax.swing.JLabel project_4_text;
    private javax.swing.JLabel project_5_text;
    // End of variables declaration//GEN-END:variables
}

class RoundedPanel extends JPanel
    {
        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(LayoutManager layout, int radius) {
            super(layout);
            cornerRadius = radius;
        }

        public RoundedPanel(LayoutManager layout, int radius, Color bgColor) {
            super(layout);
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        public RoundedPanel(int radius) {
            super();
            cornerRadius = radius;
        }

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint background
            graphics.setColor(getForeground());
            graphics.drawRoundRect(0, 0, width-1, height-1, arcs.width, arcs.height); //paint border
        }
    }